import gurobipy as gp
from gurobipy import GRB


def get_value(X):
    """Get integer value from variable, linear expression, or constant."""
    if type(X) == int:
        return X
    if type(X) == gp.LinExpr:
        return int(X.getValue())
    return int(X.x)


class Bit:
    """
    Bit class representing one bit in the hash function.

    Each bit now has only three flags:
    - ul: nonlinear flag
    - r:  contains red flag
    - b:  contains blue flag
    """

    def __init__(self, model: gp.Model, name_prefix="", bit_type=''):
        """
        Initialize bit variables.

        Parameters:
        - model: Gurobi model object
        - name_prefix: variable name prefix
        - bit_type: supports 'lr','ur','lb','ub','lg','ug','uc','c','u' or a 3-tuple.
        """
        self.model = model
        if bit_type == '':
            self.ul = model.addVar(vtype=GRB.BINARY, name=f"{name_prefix}_ul")
            self.r = model.addVar(vtype=GRB.BINARY, name=f"{name_prefix}_r")
            self.b = model.addVar(vtype=GRB.BINARY, name=f"{name_prefix}_b")
        else:
            self.init_type(model, bit_type, name_prefix)

    def init_type(self, model, bit_type, name_prefix):
        """Initialize flags based on bit type."""
        self.model = model
        if type(bit_type) == str:
            if bit_type == 'lr':      # linear red bit
                self.ul, self.r, self.b = 0, 1, 0
            elif bit_type == 'ur':    # nonlinear red bit
                self.ul, self.r, self.b = 1, 1, 0
            elif bit_type == 'lb':    # linear blue bit
                self.ul, self.r, self.b = 0, 0, 1
            elif bit_type == 'ub':    # nonlinear blue bit
                self.ul, self.r, self.b = 1, 0, 1
            elif bit_type == 'lg':    # linear red-blue combination
                self.ul, self.r, self.b = 0, 1, 1
            elif bit_type in ('uc', 'c'):  # constant
                self.ul, self.r, self.b = 0, 0, 0
            elif bit_type == 'u':     # pure nonlinear bit
                self.ul, self.r, self.b = 1, 0, 0
            elif bit_type == 'ug':    # nonlinear red-blue combination
                self.ul, self.r, self.b = 1, 1, 1
            else:
                raise ValueError(
                    "Unsupported bit type: "
                    f"{bit_type} (only 'lr','ur','lb','ub','lg','ug','uc','c','u')"
                )
        elif type(bit_type) == tuple:
            if len(bit_type) != 3:
                raise ValueError("Bit tuple type must contain exactly three entries: (ul, r, b)")
            self.ul = self._init_flag(model, bit_type[0], f"{name_prefix}_ul")
            self.r = self._init_flag(model, bit_type[1], f"{name_prefix}_r")
            self.b = self._init_flag(model, bit_type[2], f"{name_prefix}_b")
        else:
            raise ValueError("bit_type must be a string or a 3-tuple")

    @staticmethod
    def _init_flag(model, flag, name):
        if flag == '*':
            return model.addVar(vtype=GRB.BINARY, name=name)
        if flag in (0, 1):
            return flag
        raise ValueError("Bit tuple entries must be 0, 1, or '*'")

    def _get_type(self) -> str:
        """Return bit type based on flag variable values."""
        ul = get_value(self.ul)
        r = get_value(self.r)
        b = get_value(self.b)

        if ul == 1 and r == 0 and b == 0:
            return 'u'
        elif ul == 0 and r == 1 and b == 0:
            return 'lr'
        elif ul == 1 and r == 1 and b == 0:
            return 'ur'
        elif ul == 0 and r == 0 and b == 1:
            return 'lb'
        elif ul == 1 and r == 0 and b == 1:
            return 'ub'
        elif ul == 0 and r == 1 and b == 1:
            return 'lg'
        elif ul == 1 and r == 1 and b == 1:
            return 'ug'
        else:
            return 'c'


def add_or(model, z, xs, name=""):
    # z, xs are {0,1} variables or constants
    for i, x in enumerate(xs):
        model.addConstr(z >= x, name=f"{name}_or_lb_{i}")
    model.addConstr(z <= gp.quicksum(xs), name=f"{name}_or_ub")


def _add_color_or(model, output, bit, name):
    model.addConstr(output >= bit.r, name=f"{name}_r_lb")
    model.addConstr(output >= bit.b, name=f"{name}_b_lb")
    model.addConstr(output <= bit.r + bit.b, name=f"{name}_ub")


def _add_pure_u_indicator(model, output, bit, name):
    """output indicates whether bit is pure nonlinear u=(ul=1,r=0,b=0)."""
    model.addConstr(output >= bit.ul - bit.r - bit.b, name=f"{name}_lb")
    model.addConstr(output <= bit.ul, name=f"{name}_ul_ub")
    model.addConstr(output <= 1 - bit.r, name=f"{name}_r_ub")
    model.addConstr(output <= 1 - bit.b, name=f"{name}_b_ub")


def _add_create_u_constraints(model, create_u, input1, input2, has_c1, has_c2, operation_name):
    # create_u is generated by a red-blue cross product.
    model.addConstr(create_u >= input1.r + input2.b - 1, name=f"{operation_name}_create_u_r1b2_lb")
    model.addConstr(create_u >= input2.r + input1.b - 1, name=f"{operation_name}_create_u_r2b1_lb")
    model.addConstr(create_u <= input1.r + input2.r, name=f"{operation_name}_create_u_r_ub")
    model.addConstr(create_u <= input1.b + input2.b, name=f"{operation_name}_create_u_b_ub")
    model.addConstr(create_u <= has_c1, name=f"{operation_name}_create_u_c1_ub")
    model.addConstr(create_u <= has_c2, name=f"{operation_name}_create_u_c2_ub")


def xor_with_ul_input(model, inputs, output, operation_name=''):
    """XOR operation with nonlinear inputs. Returns delta_r and delta_b variables."""
    delta_r = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_delta_r")
    delta_b = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_delta_b")

    has_r = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_has_r")
    add_or(model, has_r, [i.r for i in inputs], f"{operation_name}_has_r")

    has_b = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_has_b")
    add_or(model, has_b, [i.b for i in inputs], f"{operation_name}_has_b")

    has_ul = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_has_ul")
    add_or(model, has_ul, [i.ul for i in inputs], f"{operation_name}_has_ul")

    sum_temp_u = []
    for index, bit in enumerate(inputs):
        temp = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_{index}_is_u")
        _add_pure_u_indicator(model, temp, bit, f"{operation_name}_input_{index}_is_u")
        sum_temp_u.append(temp)

    input_ub = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_ub")
    sum_temp_ub = []
    for index, bit in enumerate(inputs):
        temp = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_{index}_has_ul_b")
        model.addConstr(temp >= bit.ul + bit.b - 1)
        model.addConstr(temp <= bit.ul)
        model.addConstr(temp <= bit.b)
        sum_temp_ub.append(temp)
    add_or(model, input_ub, sum_temp_ub, f"{operation_name}_input_ub")

    model.addConstr(output.ul >= has_ul - delta_r)
    model.addConstr(output.ul <= has_ul)
    model.addConstr(output.ul <= 1 - delta_r + input_ub)
    model.addConstr(output.ul >= input_ub)

    model.addConstr(delta_r <= has_r)
    model.addConstr(delta_b <= 1 - has_ul)
    model.addConstr(delta_b <= has_b)

    model.addConstr(output.r <= has_r)
    model.addConstr(output.r >= has_r - delta_r - gp.quicksum(sum_temp_u))
    for if_u in sum_temp_u:
        model.addConstr(output.r + if_u + delta_r <= 1)

    model.addConstr(output.b <= has_b)
    model.addConstr(output.b >= has_b - gp.quicksum(sum_temp_u) - delta_b)
    for if_u in sum_temp_u:
        model.addConstr(output.b + if_u + delta_b <= 1)

    return {
        "delta_r": delta_r,
        "delta_b": delta_b,
        'has_ul': has_ul,
    }


def xor_without_ul_input(model, inputs, output, operation_name=''):
    """XOR operation without nonlinear inputs. Returns delta_r and delta_b variables."""
    delta_r = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_delta_r")
    delta_b = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_delta_b")

    sum_r = gp.quicksum([i.r for i in inputs])
    sum_b = gp.quicksum([i.b for i in inputs])

    model.addConstr(output.ul == 0)

    model.addConstr(output.r + delta_r <= sum_r)
    for bit in inputs:
        model.addConstr(output.r + delta_r >= bit.r)
    model.addConstr(output.r + delta_r <= 1)

    model.addConstr(output.b + delta_b <= sum_b)
    for bit in inputs:
        model.addConstr(output.b + delta_b >= bit.b)
    model.addConstr(output.b + delta_b <= 1)

    return {
        "delta_r": delta_r,
        "delta_b": delta_b,
        'has_ul': 0,
    }


def xor_with_ul_input_no_delta_b(model, inputs, output, operation_name=''):
    """XOR operation with nonlinear inputs and without blue cancellation."""
    delta_r = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_delta_r")

    has_r = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_has_r")
    add_or(model, has_r, [i.r for i in inputs], f"{operation_name}_has_r")

    has_b = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_has_b")
    add_or(model, has_b, [i.b for i in inputs], f"{operation_name}_has_b")

    has_ul = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_has_ul")
    add_or(model, has_ul, [i.ul for i in inputs], f"{operation_name}_has_ul")

    sum_temp_u = []
    for index, bit in enumerate(inputs):
        temp = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_{index}_is_u")
        _add_pure_u_indicator(model, temp, bit, f"{operation_name}_input_{index}_is_u")
        sum_temp_u.append(temp)

    sum_temp_ub = []
    for index, bit in enumerate(inputs):
        temp = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_{index}_has_ul_b")
        model.addConstr(temp >= bit.ul + bit.b - 1)
        model.addConstr(temp <= bit.ul)
        model.addConstr(temp <= bit.b)
        sum_temp_ub.append(temp)

    for bit in inputs:
        model.addConstr(output.ul >= bit.ul - delta_r)
    model.addConstr(output.ul <= gp.quicksum([i.ul for i in inputs]))
    model.addConstr(output.ul <= 1 - delta_r + gp.quicksum(sum_temp_ub))
    for ub in sum_temp_ub:
        model.addConstr(output.ul >= ub)

    model.addConstr(delta_r <= has_r)

    model.addConstr(output.r <= has_r)
    model.addConstr(output.r >= has_r - delta_r - gp.quicksum(sum_temp_u))
    for if_u in sum_temp_u:
        model.addConstr(output.r + if_u + delta_r <= 1)

    model.addConstr(output.b <= has_b)
    model.addConstr(output.b >= has_b - gp.quicksum(sum_temp_u))
    for t_u in sum_temp_u:
        model.addConstr(output.b <= 1 - t_u)

    return {
        "delta_r": delta_r,
        "delta_b": 0,
        'has_ul': has_ul,
    }


def and_operation(model, input1, input2, output, operation_name=''):
    has_c1 = model.addVar(vtype=GRB.BINARY, name=f'{operation_name}_has_c1')
    has_c2 = model.addVar(vtype=GRB.BINARY, name=f'{operation_name}_has_c2')
    _add_color_or(model, has_c1, input1, f"{operation_name}_has_c1")
    _add_color_or(model, has_c2, input2, f"{operation_name}_has_c2")

    new_ul = model.addVar(vtype=GRB.BINARY, name=f'{operation_name}_input_color_geq_2')
    model.addConstr(new_ul >= has_c1 + has_c2 - 1)
    model.addConstr(new_ul <= has_c1)
    model.addConstr(new_ul <= has_c2)

    model.addConstr(output.ul >= new_ul)
    model.addConstr(output.ul >= input1.ul)
    model.addConstr(output.ul >= input2.ul)
    model.addConstr(output.ul <= input1.ul + input2.ul + new_ul)

    input_u = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_u")
    pure_u_flags = []
    for index, bit in enumerate([input1, input2]):
        temp = model.addVar(vtype=GRB.BINARY, name=f"{operation_name}_input_{index}_is_u")
        _add_pure_u_indicator(model, temp, bit, f"{operation_name}_input_{index}_is_u")
        pure_u_flags.append(temp)
    add_or(model, input_u, pure_u_flags, f"{operation_name}_input_u")

    create_u = model.addVar(vtype=GRB.BINARY, name=f'{operation_name}_create_u')
    _add_create_u_constraints(model, create_u, input1, input2, has_c1, has_c2, operation_name)

    has_r = model.addVar(vtype=GRB.BINARY, name=f'{operation_name}_has_r')
    has_b = model.addVar(vtype=GRB.BINARY, name=f'{operation_name}_has_b')
    add_or(model, has_r, [input1.r, input2.r], f"{operation_name}_has_r")
    add_or(model, has_b, [input1.b, input2.b], f"{operation_name}_has_b")

    model.addConstr(output.r <= has_r)
    model.addConstr(3 * output.r >= has_r - input_u - create_u)
    model.addConstr(output.r <= 1 - input_u)
    model.addConstr(output.r <= 1 - create_u)

    model.addConstr(output.b <= has_b)
    model.addConstr(3 * output.b >= has_b - input_u - create_u)
    model.addConstr(output.b <= 1 - input_u)
    model.addConstr(output.b <= 1 - create_u)

    return {}
